[package]
name = "camel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5" # random generetaor via thread

# for displaying the gamae
unicode-width = "0.1.5"
terminal_size = "0.2.3"